# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/kiki1/Desktop/assignments/Zynq_termprj/gfx_source/Zybo-Z7-Master.xdc

# Block Designs: bd/termprj_top/termprj_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top || ORIG_REF_NAME==termprj_top} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_processing_system7_0_1/termprj_top_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_processing_system7_0_1 || ORIG_REF_NAME==termprj_top_processing_system7_0_1} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_xbar_0/termprj_top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_xbar_0 || ORIG_REF_NAME==termprj_top_xbar_0} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_ps7_0_axi_periph_1/termprj_top_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_ps7_0_axi_periph_1 || ORIG_REF_NAME==termprj_top_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_rst_ps7_0_53M_0/termprj_top_rst_ps7_0_53M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_rst_ps7_0_53M_0 || ORIG_REF_NAME==termprj_top_rst_ps7_0_53M_0} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_util_ds_buf_0_0/termprj_top_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_util_ds_buf_0_0 || ORIG_REF_NAME==termprj_top_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_bridgeio_0_0/termprj_top_bridgeio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_bridgeio_0_0 || ORIG_REF_NAME==termprj_top_bridgeio_0_0} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_rotaryio_0_0/termprj_top_rotaryio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_rotaryio_0_0 || ORIG_REF_NAME==termprj_top_rotaryio_0_0} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_axi_gpio_0_1/termprj_top_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_axi_gpio_0_1 || ORIG_REF_NAME==termprj_top_axi_gpio_0_1} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_clk_wiz_0_2/termprj_top_clk_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_clk_wiz_0_2 || ORIG_REF_NAME==termprj_top_clk_wiz_0_2} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_gfx_top_0_1/termprj_top_gfx_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_gfx_top_0_1 || ORIG_REF_NAME==termprj_top_gfx_top_0_1} -quiet] -quiet

# IP: bd/termprj_top/ip/termprj_top_auto_pc_0/termprj_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==termprj_top_auto_pc_0 || ORIG_REF_NAME==termprj_top_auto_pc_0} -quiet] -quiet

# XDC: bd/termprj_top/termprj_top_ooc.xdc
